apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -deployment-b2

commonLabels:
  app: app-deployment-b2

resources:
  - ../../../../base

patchesStrategicMerge:
  - patch.yaml
