apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: namespace-b
nameSuffix: -deployment-b

commonLabels:
  app: app-deployment-b

resources:
  - ../../../../base

patchesStrategicMerge:
  - patch.yaml
