apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -deployment-a1

commonLabels:
  app: app-deployment-a1

resources:
- ../../../../base
- namespace.yaml
patchesStrategicMerge:
- patch.yaml
