apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -deployment-a2

commonLabels:
  app: app-deployment-a2

resources:
  - ../../../../base

patchesStrategicMerge:
  - patch.yaml

