apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: namespace-a
nameSuffix: -deployment-a

commonLabels:
  app: app-deployment-a

resources:
  - ../../../../base

patchesStrategicMerge:
  - patch.yaml
